project:
  type: website
  
website:
  title: "Deep learning with satellite & aerial imagery"
  sidebar:
    style: "docked"
    search: true
    logo: "images/logo.png"
    tools:
      - icon: display
        href: https://www.satellite-image-deep-learning.com/
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/satellite-image-deep-learning/course
          - text: Report an issue
            url:  https://github.com/satellite-image-deep-learning/course/issues
      - icon: youtube
        href: https://www.youtube.com/playlist?list=PLHifi5Wnkifd5ZndO2ichD_7nnB26eDBj
    contents:
      - welcome.qmd
      - introduction.qmd
      - section: "Basic techniques"
        contents:
          - classification.qmd
          - regression.qmd
          - segmentation.qmd
          - object-detection.qmd
      - section: "Advanced techniques"
        contents:
          - sar.qmd
          - hyperspectral.qmd
          - super-resolution.qmd
          - data-fusion.qmd
          - time-series.qmd
          - clouds.qmd
      - section: "Applications"
        contents:
          - urban-mapping.qmd
          - crop-monitoring.qmd
          - disaster-response.qmd
      - section: "Appendix"
        contents:
          - dataset-preparation.qmd
          - imaging-physics.qmd
          - mlops.qmd

format:
  html:
    theme:
      light: cosmo
      dark: darkly