project:
  type: book
  
book:
  title: Deep learning with satellite & aerial imagery
  author: Robin Cole
  logo: logo.png
  repo-url: https://github.com/satellite-image-deep-learning/course
  repo-branch: main
  chapters:
    - index.qmd
    - ch1.ipynb
    - ch2.ipynb
  appendices:
    - resources.qmd

format:
  html:
    theme: cosmo