project:
  type: website
  
website:
  title: "Deep learning with satellite & aerial imagery"
  sidebar:
    style: "docked"
    search: true
    logo: "images/logo.png"
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/satellite-image-deep-learning/course
          - text: Report an issue
            url:  https://github.com/satellite-image-deep-learning/course/issues
    contents:
      - welcome.md
      - introduction.md
      - classification.md
      - segmentation.md

format:
  html:
    theme: cosmo